version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: jasmin
      POSTGRES_USER: jasmin
      POSTGRES_PASSWORD: jasmin24
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
